### ISSUE TITLE
Support for Expr in LazyFrame LogicPlan?

### ISSUE THREAD

**Issue by yutiansut** [mithril-security/bastionlab#126]
currently seems that all support methods are based on LazyFrame, however

```
all_rdfs[0]\
    .select([pl.col('xx'), pl.col('yy')])\
    .groupby(pl.col('xx'))\
    .agg(pl.col('yy').pct_change())\
    .collect()\
    .fetch()
```
will raised a error for 
```
Error("the enum variant Expr::AnonymousFunction cannot be serialized", line: 0, column: 0)
```

this is wired and while checked the souce code 
[code](https://github.com/mithril-security/bastionlab/blob/master/client/src/bastionlab/polars/remote_polars.py#L183)
```python
@delegate(
    target_cls=pl.LazyFrame,
    target_attr="_inner",
    f_names=[
        "__bool__",
        "__contains__",
        "__copy__",
        "__deepcopy__",
        "__getitem__",
    ],
)
@delegate(
    target_cls=pl.LazyFrame,
    target_attr="_inner",
    f_names=[
        "sort",
        "cache",
        "filter",
        "select",
        "with_columns",
        "with_context",
        "with_column",
        "drop",
        "rename",
        "reverse",
        "shift",
        "shift_and_fill",
        "slice",
        "limit",
        "head",
        "tail",
        "last",
        "first",
        "with_row_count",
        "take_every",
        "fill_null",
        "fill_nan",
        "std",
        "var",
        "max",
        "min",
        "sum",
        "mean",
        "median",
        "quantile",
        "explode",
        "unique",
        "drop_nulls",
        "melt",
        "interpolate",
        "unnest",
    ],
    wrap=True,
)
``` 

seems the method supported is only on the lazyframe level, not the ```Expr``` level

@theolebever @ShannonSD @cchudant @dhalf

**Comment by yutiansut** [comment]
while we try to use ```groupby.agg([])```

the function on pl.col is a Expr exactly, maybe thisis not a right plan for using the ```Lazyframe```'s function to write this logicplan

**Comment by dhalf** [comment]
Pasting our discussion on Discord (https://discord.com/channels/937665890420424746/1047069127128399973/1051702532231135262) here so that it can benefit others.

[Lucas]
Hello tquant! Thanks for your interest in the project and for raising an issue.
I believe you cannot serialize the query because it uses the pct_change method which is represented as an anonymous function in the logical plan.
Variants of the Expr enum (in the Rust backend) are already not serializable in vanilla polars (for technical reasons) and we chose not to add a way to make them serializable for security reasons. In fact, this would be equivalent to giving the user the opportunity to execute arbitrary Python (or Rust) code on the server, something we seek to avoid at all costs. Now, we also have to admit that user defined functions are a very import tool for data scientist and that a big part of methods/functions for statistics rely on them as an implementation mechanism. As a first step towards securely supporting them, we added the apply_udf method to our RemoteLazyFrame class that takes any torch compatible function and serializes it as TorchScript a very limited subset of Python which we believe is safer. Although not as ergonomic as the Expr API most use cases of anonymous functions can be rewritten using apply_udf. We also plan to add ways of providing an API for udfs and methods that rely on them that is closer to polars' while retaining the TorchScript approach.
To solve your problem, I suggest you create a copy of the yy column to which you apply the pct_change operation using apply_udf. Then you can GroupBy/Agg using the new column directly. The difficult part is to rewrite pct_change in a TorchScript compatible way. Note that the argument of this function is an entire series represented as a torch tensor. I would do it this way:
- Create a copy of the input "series tensor" and shift all elements one location to the right.
- Subtract the shifted copy to the initial "series tensor".
- Divide the result by the shifted "series tensor".

```py
>>> import torch
>>> a = torch.tensor([1,2,3,4])
>>> shifted_a = torch.roll(a, 1)
>>> shifted_a
tensor([4, 1, 2, 3])
>>> (a - shifted_a)/shifted_a
tensor([-0.7500,  1.0000,  0.5000,  0.3333])
```

Only the first element of the result is not meaningful and would be null using the real pct_change.

You can find an example of this approach with apply_udf in the histplot method code https://github.com/mithril-security/bastionlab/blob/5d2ae69c05e6a1135f48b9fa74ab71a0d12fcbab/client/src/bastionlab/polars/remote_polars.py#L482-L492

The full solution could look like:
```py
class PctChange(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x):
        shifted_x = torch.roll(a, 1)
        return (x - shifted_x)/shifted_x

(
    all_rdfs[0]
    .select([pl.col('xx'), pl.col('yy')])
    .with_column(pl.col('yy').alias('pct_change_yy'))
    .apply_udf('pct_change_yy', PctChange())
    .groupby(pl.col('xx'))
    .agg(pl.col('pct_change_yy'))
    .collect()
    .fetch()
)
```

[tquant]
yep, thanks for reply, this is really a great solution for adding a udf with tensor backend, however the base calc agg methods is somuch, so this is not a possible way to rewrite every Expr from polars to torch, i'm curios about why
```
Variants of the Expr enum (in the Rust backend) are already not serializable in vanilla polars (for technical reasons) and we chose not to add a way to make them serializable for security reasons.
```
in my view of polars: it gives the way like database backend for a lazy calc and optimized logicalplan+physical plan,  and also it gaves comprehensive Expr for user to transform the data easily, if we don't support the Expr, this may actually equal to rewrite the whole polars at all, and also the cost of copy is hugh while the dataset in above 500GB+
@Lucas

[Daniel]
@tquant Just dropping by, I think depending on what users demand, we (or a contributor) could do a hand-crafted implementation of a udf, open a PR and add it to a pool of "unsafe but checked" functions. This answers both constraints: 
- we can implement the UDF in a much more optimized manner
- we can check the UDF using out of scope code does not compromise data
It is a bit less smooth but could work, and it would make sense to receive contributors' PR for this, approve it, and it to the pool of verified udf
@Lucas What do you think?

[Lucas]
Polars developers marked some of the variants of Expr as non serializable using a serde attribute. This means that trying to serialize them results in a panic. I assume they did that because properly serializing a closure is hard. In addition, we chose not to implement it ourselves for the security reasons I mentioned earlier.
I understand your point regarding performance and I agree with you: splitting the logical plan to insert custom TorchScript UDF may prevent some optimizations.
However, if we authorized to run any Python function on the server our solution would be comparable to running an open jupyter server. Whatever technique you use to protect it, an attacker is still able to craft some code that circumvent it because they can inject whatever code they want.

Now, as Daniel suggested, we (or contributors) might (re)implement functions that are useful for analytics in such a way that they can be serialized in TorchScript and potentially integrated to the API in a more usable way. It may take time to get all the functions polars already supports but it is in my opinion the only way to retain the security guarantees that are the foundation of this project.
Regarding the copy of the column that is necessary to apply the udf without destroying initial data, my guess is that the cost of the computation dominates the one of the copy. But this is definitely something we will look into.
