### ISSUE TITLE
Misleading error: The enum variant LogicalPlan::Error cannot be serialized

### ISSUE THREAD

**Issue by cchudant** [mithril-security/bastionlab#181]
Reproduction
```py
repro_rdf.select(pl.col("i do not exist")).collect().fetch()
```
Error should be something like "column does not exist"

instead, we have
```py
ValueError: Error("the enum variant LogicalPlan::Error cannot be serialized", line: 0, column: 0)
```

Theory is that polars returns the right error, it returns something like "column does not exist" but polars does not know how to serialize LogicalPlan::Error(x) (i don't know if client/server side)
expected: It should parse it correctly and show the error correctly

**Comment by dhalf** [comment]
Yes, the right thing to do is to retrieve the error from the logical plan. But this is tricky...
The problem is that we do not have direct access to the logical plan from the Python code: the only way to get the plan is to serialize it on the Rust side and use FFI to get a string which can be achieved with `LazyFrame.write_json`.
As this involves a serialization step, the error will be raised on the Rust side and we won't get neither the plan nor the actual error message...
